import os
from PyQt6.QtWidgets import QMainWindow, QVBoxLayout, QWidget, QMessageBox
from PyQt6.QtWebEngineWidgets import QWebEngineView
from PyQt6.QtWebEngineCore import QWebEngineProfile
from PyQt6.QtCore import QUrl, pyqtSignal
from PyQt6.QtNetwork import QNetworkCookie

import json
COOKIES_FILE = os.path.abspath("cookies.txt")
USER_AGENT_FILE = os.path.abspath("user_agent.txt")

class BrowserWindow(QMainWindow):
    cookies_saved = pyqtSignal(str)

    def __init__(self):
        super().__init__()
        self.setWindowTitle("Login to YouTube")
        self.resize(800, 600)
        self.cookies_dict = {}

        self.central_widget = QWidget()
        self.setCentralWidget(self.central_widget)
        self.layout = QVBoxLayout(self.central_widget)

        self.profile = QWebEngineProfile("youtube_login_profile", self)
        self.profile.setPersistentCookiesPolicy(QWebEngineProfile.PersistentCookiesPolicy.ForcePersistentCookies)

        self.profile.cookieStore().cookieAdded.connect(self.on_cookie_added)
        self.profile.cookieStore().loadAllCookies()

        self.browser = QWebEngineView(self)

        # We need to set the profile to the page. Wait, QWebEnginePage takes profile in constructor.
        from PyQt6.QtWebEngineCore import QWebEnginePage
        self.page = QWebEnginePage(self.profile, self.browser)
        self.browser.setPage(self.page)

        self.layout.addWidget(self.browser)

        self.browser.setUrl(QUrl("https://accounts.google.com/ServiceLogin?service=youtube&continue=https://www.youtube.com/"))

    def on_cookie_added(self, cookie):
        domain = cookie.domain()
        name = str(cookie.name(), 'utf-8')
        # Use domain + name as a unique key to prevent duplicates
        # Copy the cookie to prevent segfaults when Qt destroys the original C++ object
        self.cookies_dict[f"{domain}_{name}"] = QNetworkCookie(cookie)

    def write_cookies_to_file(self):
        try:
            with open(COOKIES_FILE, "w", encoding="utf-8") as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# This file was generated by YouTube Fast Saver\n")
                f.write("# https://curl.haxx.se/rfc/cookie_spec.html\n\n")

                for cookie in self.cookies_dict.values():
                    domain = cookie.domain()

                    # yt-dlp requires HttpOnly flag to be prefixed as `#HttpOnly_` before the domain
                    prefix = ""
                    if cookie.isHttpOnly():
                        prefix = "#HttpOnly_"

                    include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
                    path = cookie.path()
                    secure = "TRUE" if cookie.isSecure() else "FALSE"

                    # Expiration date
                    expires = str(int(cookie.expirationDate().toSecsSinceEpoch())) if cookie.expirationDate().isValid() else "0"
                    name = str(cookie.name(), 'utf-8')
                    value = str(cookie.value(), 'utf-8')

                    line = f"{prefix}{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n"
                    f.write(line)

            self.cookies_saved.emit(COOKIES_FILE)
        except Exception as e:
            print(f"Error saving cookies: {e}")

    def closeEvent(self, event):
        self.write_cookies_to_file()
        super().closeEvent(event)
