import os
from PyQt6.QtWidgets import QMainWindow, QVBoxLayout, QWidget, QMessageBox
from PyQt6.QtWebEngineWidgets import QWebEngineView
from PyQt6.QtWebEngineCore import QWebEngineProfile
from PyQt6.QtCore import QUrl, pyqtSignal

import json
COOKIES_FILE = os.path.abspath("cookies.txt")
USER_AGENT_FILE = os.path.abspath("user_agent.txt")

class BrowserWindow(QMainWindow):
    cookies_saved = pyqtSignal(str)

    def __init__(self):
        super().__init__()
        self.setWindowTitle("Login to YouTube")
        self.resize(800, 600)

        self.central_widget = QWidget()
        self.setCentralWidget(self.central_widget)
        self.layout = QVBoxLayout(self.central_widget)

        self.profile = QWebEngineProfile("youtube_login_profile", self)
        self.profile.setPersistentCookiesPolicy(QWebEngineProfile.PersistentCookiesPolicy.ForcePersistentCookies)

        self.browser = QWebEngineView(self)

        self.browser.setPage(self.browser.page())

        # We need to set the profile to the page. Wait, QWebEnginePage takes profile in constructor.
        from PyQt6.QtWebEngineCore import QWebEnginePage
        self.page = QWebEnginePage(self.profile, self.browser)
        self.browser.setPage(self.page)

        self.layout.addWidget(self.browser)

        self.browser.setUrl(QUrl("https://accounts.google.com/ServiceLogin?service=youtube&continue=https://www.youtube.com/"))

        self.browser.loadFinished.connect(self.on_load_finished)

    def on_load_finished(self, ok):
        # Every time a page loads, we try to save cookies
        if ok:
            self.save_cookies()

    def save_cookies(self):
        cookie_store = self.profile.cookieStore()
        self.cookies_dict = {}

        # Connect to intercept cookies BEFORE loading them
        try:
            cookie_store.cookieAdded.disconnect(self.on_cookie_added)
        except Exception:
            pass
        self._cookie_added_conn = cookie_store.cookieAdded.connect(self.on_cookie_added)

        # This is asynchronous
        cookie_store.loadAllCookies()

        # Wait longer to ensure all cookies load, especially YouTube auth cookies
        from PyQt6.QtCore import QTimer
        QTimer.singleShot(3000, self.write_cookies_to_file)

    def on_cookie_added(self, cookie):
        domain = cookie.domain()
        name = str(cookie.name(), 'utf-8')
        # Use domain + name as a unique key to prevent duplicates
        self.cookies_dict[f"{domain}_{name}"] = cookie

    def write_cookies_to_file(self):
        try:
            with open(COOKIES_FILE, "w", encoding="utf-8") as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# This file was generated by YouTube Fast Saver\n")
                f.write("# https://curl.haxx.se/rfc/cookie_spec.html\n\n")

                for cookie in self.cookies_dict.values():
                    domain = cookie.domain()

                    # yt-dlp requires HttpOnly flag to be prefixed as `#HttpOnly_` before the domain
                    prefix = ""
                    if cookie.isHttpOnly():
                        prefix = "#HttpOnly_"

                    include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
                    path = cookie.path()
                    secure = "TRUE" if cookie.isSecure() else "FALSE"

                    # Expiration date
                    expires = str(int(cookie.expirationDate().toSecsSinceEpoch())) if cookie.expirationDate().isValid() else "0"
                    name = str(cookie.name(), 'utf-8')
                    value = str(cookie.value(), 'utf-8')

                    line = f"{prefix}{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n"
                    f.write(line)

            self.cookies_saved.emit(COOKIES_FILE)

            try:
                self.profile.cookieStore().cookieAdded.disconnect(self.on_cookie_added)
            except Exception:
                pass
        except Exception as e:
            print(f"Error saving cookies: {e}")

    def closeEvent(self, event):
        self.save_cookies()
        super().closeEvent(event)
