import PyQt6.QtGui as QtGui
from PyQt6.QtGui import QPalette, QColor

def apply_theme(app, theme_name="light"):
    if theme_name == "dark":
        app.setStyle("Fusion")
        dark_palette = QPalette()
        dark_palette.setColor(QPalette.ColorRole.Window, QColor(53, 53, 53))
        dark_palette.setColor(QPalette.ColorRole.WindowText, QColor(255, 255, 255))
        dark_palette.setColor(QPalette.ColorRole.Base, QColor(25, 25, 25))
        dark_palette.setColor(QPalette.ColorRole.AlternateBase, QColor(53, 53, 53))
        dark_palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(255, 255, 255))
        dark_palette.setColor(QPalette.ColorRole.ToolTipText, QColor(255, 255, 255))
        dark_palette.setColor(QPalette.ColorRole.Text, QColor(255, 255, 255))
        dark_palette.setColor(QPalette.ColorRole.Button, QColor(53, 53, 53))
        dark_palette.setColor(QPalette.ColorRole.ButtonText, QColor(255, 255, 255))
        dark_palette.setColor(QPalette.ColorRole.BrightText, QColor(255, 0, 0))
        dark_palette.setColor(QPalette.ColorRole.Link, QColor(42, 130, 218))
        dark_palette.setColor(QPalette.ColorRole.Highlight, QColor(42, 130, 218))
        dark_palette.setColor(QPalette.ColorRole.HighlightedText, QColor(0, 0, 0))
        app.setPalette(dark_palette)
        app.setStyleSheet("QToolTip { color: #ffffff; background-color: #2a82da; border: 1px solid white; }")
    elif theme_name == "blue":
        app.setStyle("Fusion")
        blue_palette = QPalette()
        blue_palette.setColor(QPalette.ColorRole.Window, QColor(30, 60, 90))
        blue_palette.setColor(QPalette.ColorRole.WindowText, QColor(255, 255, 255))
        blue_palette.setColor(QPalette.ColorRole.Base, QColor(20, 40, 60))
        blue_palette.setColor(QPalette.ColorRole.AlternateBase, QColor(30, 60, 90))
        blue_palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(255, 255, 255))
        blue_palette.setColor(QPalette.ColorRole.ToolTipText, QColor(255, 255, 255))
        blue_palette.setColor(QPalette.ColorRole.Text, QColor(255, 255, 255))
        blue_palette.setColor(QPalette.ColorRole.Button, QColor(40, 80, 120))
        blue_palette.setColor(QPalette.ColorRole.ButtonText, QColor(255, 255, 255))
        blue_palette.setColor(QPalette.ColorRole.Highlight, QColor(100, 150, 200))
        blue_palette.setColor(QPalette.ColorRole.HighlightedText, QColor(255, 255, 255))
        app.setPalette(blue_palette)
        app.setStyleSheet("QToolTip { color: #ffffff; background-color: #6496c8; border: 1px solid white; }")
    else: # Light (default)
        app.setStyle("Fusion")
        app.setPalette(app.style().standardPalette())
        app.setStyleSheet("")
